### ISSUE TITLE
Fail to build using cross

### ISSUE THREAD

**Issue by appaquet** [baoyachi/shadow-rs#100]
Last release (v0.13.0) doesn't build anymore when using [cross](https://github.com/cross-rs/cross).

Trying to build the examples from the repository with:

`cross build -p example_shadow --target x86_64-unknown-linux-gnu `

leads to:
```
error: failed to run custom build command for `example_shadow v0.1.8-beta3 (/project/example_shadow)`

Caused by:
  process didn't exit successfully: `/target/debug/build/example_shadow-97a9495984081d63/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/time.rs:21:40
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The reasons it fails is that the `tz-rs` crates tries to parse the timezone data from `/etc/localtime`, which probably doesn't exist in cross's Docker image. See: https://github.com/x-hgg-x/tz-rs/blob/master/src/timezone/mod.rs#L518

A good alternative for me would be to expose a way to either fallback to UTC or simply force UTC.

Thanks!

**Comment by baoyachi** [comment]
Oh, I will fix right now

**Comment by baoyachi** [comment]
@appaquet Thx for your report. 

Now, fix with https://github.com/baoyachi/shadow-rs/pull/102

Upgarde shadow-rs version

```bash
...
[dependencies]
shadow-rs = "0.13.1"
...
```
