### ISSUE TITLE
Allow disabling the CARGO_TREE variable in the output as it can contain sensitive information

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [baoyachi/shadow-rs#114]
`CARGO_TREE` includes the dependency tree. This in turn will include the full file system path for any path dependencies, as is common for multi-crate projects. The file system path may contain sensitive information, and I do not want to rely on the linker removing CARGO_TREE from the built binary if I don't use it; I must be sure that the compiler never sees it.

Therefore I'm just asking for the ability to disable this build information variable via a feature flag or a build script configuration option.

**Comment by baoyachi** [comment]
I can support. I'm try do it.

**Comment by baoyachi** [comment]
hi @kleinesfilmroellchen 
I'm sorry I was a little late in solving this issue, but the new version can solve the problem you mentioned. Please use :

```toml
shadow-rs = "0.20.0"
```

**Comment by kleinesfilmroellchen** [comment]
@baoyachi tyvm!
