### ISSUE TITLE
Static dependency tree

### ISSUE THREAD

**Issue by stevefan1999-personal** [baoyachi/shadow-rs#117]
I need this so I can match the kernel dependencies to match the kernel module but I don't want a whole `cargo tree`. I just want to compare the structures programatically, is is possible to just dump the data structure only?

**Comment by baoyachi** [comment]
I'm try do it.

**Comment by baoyachi** [comment]
Now,you can use [CARGO_METADATA](https://docs.rs/shadow-rs/latest/shadow_rs/constant.CARGO_METADATA.html) get value.
