### ISSUE TITLE
A way to get closest tag from current commit

### ISSUE THREAD

**Issue by ImUrX** [baoyachi/shadow-rs#130]
We are representing versioning with git and I want to do ``v1.0.0/commit_hash`` instead of just ``commit_hash``. Maybe adding a new constant called ``LAST_TAG`` would be nice.
In git commands for doing this, ``git describe --abbrev=0 HEAD`` should work out.

**Comment by baoyachi** [comment]
👍

**Comment by baoyachi** [comment]
@ImUrX Maybe you want use this git commands: `git describe --tags --abbrev=0`

**Comment by ImUrX** [comment]
Do you mind telling me the difference?

**Comment by baoyachi** [comment]
@ImUrX  When I use this commands on my mac os :`git describe --abbrev=0 HEAD`, it's make error
```bash
➜  shadow-rs git:(master) git describe --abbrev=0 HEAD
fatal: No annotated tags can describe '57280c4a24b3b9a24feec5dfc09b5066cac7fde8'.
However, there were unannotated tags: try --tags.
```
Then add `--tags` exec ok
```bash
➜  shadow-rs git:(master) git describe --tags --abbrev=0 HEAD
v0.20.1
➜  shadow-rs git:(master)
```

## Git version
```bash
➜  shadow-rs git:(master) git version
git version 2.39.2
➜  shadow-rs git:(master)
```

**Comment by baoyachi** [comment]
@ImUrX So, Do you still anticipate the LAST_TAG feature?

If you are looking forward to this feature, I can complete it.

**Comment by ImUrX** [comment]
Yeah, it would be nice having it!

**Comment by baoyachi** [comment]
@ImUrX Now, you can upgrade new version use `LAST_TAG ` feature.

```toml
shadow-rs = "0.21.0"
```
