### ISSUE TITLE
Issue with `cargo publish` ?

### ISSUE THREAD

**Issue by ChristopherRabotin** [baoyachi/shadow-rs#135]
Hi there,

In my `build.rs` file, I've got the following as per the instructions:
```rust
fn main() -> shadow_rs::SdResult<()> {
    shadow_rs::new()
}
```

When I try to publish the package, I get the following error (full [traceback here](https://github.com/nyx-space/nyx/actions/runs/5080952451/jobs/9130014940)):
```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: /home/runner/work/nyx/nyx/target/package/nyx-space-2.0.0-alpha/Cargo.lock
```

I diff'd the `Cargo.lock` file before and after running `cargo publish` on my machine instead of the github action, and it seems that the cargo.lock file didn't actually change.

Any idea what could be causing this issue?
Thanks

**Comment by baoyachi** [comment]
@ChristopherRabotin Sorry, I will try to reproduce this problem later.

**Comment by baoyachi** [comment]
@ChristopherRabotin fixed this in version 0.23. Please use 
```toml
shadow-rs = "0.23.0"
```

**Comment by tisonkun** [comment]
With `shadow-rs = { version = "0.35" }` and this issue happens again. May I see the fix you made and try to understand what happens here?

@baoyachi

**Comment by tisonkun** [comment]
Perhaps related to https://github.com/baoyachi/shadow-rs/issues/163
