### ISSUE TITLE
Can we add git commit count to build information?

### ISSUE THREAD

**Issue by tiann** [baoyachi/shadow-rs#137]
The result of `git rev-list --count HEAD` is sometimes useful to generate version code.

**Comment by baoyachi** [comment]
Hi @tiann 
`shadow-rs` support  extended [hook function](https://docs.rs/shadow-rs/latest/shadow_rs/fn.new_hook.html).

If you want add `git rev-list --count HEAD ` result in you build project. I suggest use `new_hook` function.

The detail example ,please see 
* [build.rs](https://github.com/baoyachi/shadow-rs/blob/master/example_shadow_hook/build.rs)
* [main.rs](https://github.com/baoyachi/shadow-rs/blob/master/example_shadow_hook/src/main.rs)

**Comment by tiann** [comment]
If using a hook, we may need to integrate the git2 dependency or install git. I would be happy to submit a PR if you are willing to accept this feature.

**Comment by baoyachi** [comment]
Currently, the feature is not needed.
