### ISSUE TITLE
Clippy lint `clippy::needless-raw-string-hashes` chokes on shadow-rs generated code

### ISSUE THREAD

**Issue by segevfiner** [baoyachi/shadow-rs#141]
See https://github.com/segevfiner/keepawake-rs/actions/runs/6163069647/job/16725828216. I guess the generated file either needs an `#!allow(clippy::needless-raw-string-hashes)` file level attribute, or only adding the hashes when actually needed.

**Comment by baoyachi** [comment]
Thank you. I will resolve it later.

**Comment by baoyachi** [comment]
New version publised, please use :
```toml
shadow-rs = "0.24.0"
```
