### ISSUE TITLE
Is build = "build.rs" really needed?

### ISSUE THREAD

**Issue by szabgab** [baoyachi/shadow-rs#150]
I just tried the example in the [readme](https://crates.io/crates/shadow-rs) without adding

```
[package]
build = "build.rs"
```

and it worked as I expected. Using rustc 1.76.0

Is that entry really needed?

**Comment by baoyachi** [comment]
```tom
[package]
build = "build.rs"
```

This is an optional addition where, by default, `build` points to the `build.rs` file. It is recommended to use it as such. However, if your build script file is not named `build.rs`, please manually specify it. For example: `build = "gen.rs"`.

Thank you for your question; I will improve the documentation accordingly.
