### ISSUE TITLE
Git branch and commit empty in Docker after updating from 0.29.0

### ISSUE THREAD

**Issue by Esgrove** [baoyachi/shadow-rs#173]
I have an API that runs in Docker. 

In my dockerfile, I copy the .git dir to the docker builder image so shadow can read the values.

```
COPY api/Cargo.toml api/Cargo.lock api/build.rs api/.cargo/config.toml .git ./
```

However, after updating to 0.31.0 and 0.31.1, the git variables that I use are empty so shadow-rs no longer works correctly when building inside Docker.

**Comment by Esgrove** [comment]
Turns out the amazon linux docker image does not have `git` available by default. Works after installing git in the image first.

Would you good for you to document that this crate now requires git to be available unlike previously. The [CHANGELOG.md](https://github.com/baoyachi/shadow-rs/blob/master/CHANGELOG.md) document has not been updated in two years so please either start updating it again or just remove it since currently it is not providing any value.

**Comment by baoyachi** [comment]
@Esgrove  Please use new publised version：

```toml
shadow-rs = "0.32.0"
```
