### ISSUE TITLE
Configure shadow-rs to run only once during development

### ISSUE THREAD

**Issue by leaf-potato** [baoyachi/shadow-rs#175]
After using shadow-rs, even if no code is modified, the code generated by shadow-rs will cause the code that depends on shadow-rs to be recompiled, which is very bad in large projects. If shadow-rs can be configured to run only once during local development, the user experience will be better.

**Comment by baoyachi** [comment]
Thank you for the feedback. It should need to solve it.

**Comment by baoyachi** [comment]
Hi @leaf-potato  ,apologies for the delayed response to this question. Additionally, the desired solution has finally arrived.

New version publised, please use :
```
shadow-rs = "0.37.0"
```

The code in build.rs, use `BuildPattern::Lazy`.Please see detail:https://github.com/baoyachi/shadow-rs?tab=readme-ov-file#buildpattern

```diff
fn main() {
	ShadowBuilder::builder()
+		.build_pattern(BuildPattern::Lazy)
		.build().unwrap();
}

```

**Comment by baoyachi** [comment]
I will close it. If there is a problem, it can be reopened.

**Comment by leaf-potato** [comment]
@baoyachi This is very good, thank you very much!
