### ISSUE TITLE
Remove the generated Cargo.lock after build

### ISSUE THREAD

**Issue by tisonkun** [baoyachi/shadow-rs#184]
It seems this code snippet will generate a `Cargo.lock` file that fails `cargo publish` as described in #135.

https://github.com/baoyachi/shadow-rs/blob/4358b4a0949fc50e50860ee625bc4dbfdc79166a/src/env.rs#L122-L130

@weihanglo suggested in https://github.com/rust-lang/cargo/issues/12195 that we may delete the `Cargo.lock` after build.

**Comment by tisonkun** [comment]
Currently work it around by add this line to the `build.rs` file:

```rust
// Ref - https://github.com/rust-lang/cargo/issues/12195.
    let _ = std::fs::remove_file(Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.lock"));
```

**Comment by weihanglo** [comment]
BTW `--locfile-path` has been implemented: <https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#lockfile-path>
While it is still an unstable feature, it would be appreciated if you could give feedback :)

**Comment by baoyachi** [comment]
@tisonkun The next version will fix it.

**Comment by tisonkun** [comment]
@baoyachi Cool! Would you please link the related changes to this issue so that we can cross ref each other?

**Comment by baoyachi** [comment]
> @baoyachi Cool! Would you please link the related changes to this issue so that we can cross ref each other?

No problem.

**Comment by baoyachi** [comment]
@tisonkun New version publised,please use:
```toml
shadow-rs = "0.35.1"
```

By the way, the code with `let _ = std::fs::remove_file(Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.lock"));` can be remove in [morax](https://github.com/tisonkun/morax) .

**Comment by tisonkun** [comment]
Update it. Thank you!
