### ISSUE TITLE
Any plans to support showing cc version?

### ISSUE THREAD

**Issue by sshwy** [baoyachi/shadow-rs#189]
As the title suggests. I'm currently developing a project that requires some c source files compilation using `cc`. And I wish to add the version of `cc` in the build information.

**Comment by baoyachi** [comment]
Hi @sshwy 
`shadow-rs` support  extended [hook function](https://docs.rs/shadow-rs/latest/shadow_rs/fn.new_hook.html).

If you want add `cc ` result in you build project. I suggest use `new_hook` function.

The detail example ,please see 
* [build.rs](https://github.com/baoyachi/shadow-rs/blob/master/example_shadow_hook/build.rs)
* [main.rs](https://github.com/baoyachi/shadow-rs/blob/master/example_shadow_hook/src/main.rs)

**Comment by sshwy** [comment]
Thank you for your advice! That'll work for my project.

**Comment by baoyachi** [comment]
I feel happy for you. If you have any questions, please consult again.
