### ISSUE TITLE
🌟 collection who use this project ✨✨✨

### ISSUE THREAD

**Issue by baoyachi** [baoyachi/shadow-rs#19]

**Comment by baoyachi** [comment]
* https://github.com/nushell/nushell

**Comment by Cypher1** [comment]
Thanks @baoyachi I'm using shadow-rs in https://github.com/project-oak/arcsjs-provable/pull/25

**Comment by Cypher1** [comment]
Our use of shadow-rs is now live at https://project-oak.github.io/arcsjs-provable/ibis/playground/
Thanks again!

**Comment by baoyachi** [comment]
> Our use of shadow-rs is now live at https://project-oak.github.io/arcsjs-provable/ibis/playground/ Thanks again!

Wow,It's interesting
