### ISSUE TITLE
Re-export shadow-rs

### ISSUE THREAD

**Issue by Nugine** [baoyachi/shadow-rs#191]
The constants refer to `shadow_rs` directly. If there is a cli framework that wants to bundle and re-export `shadow-rs`, it will not work.

https://github.com/baoyachi/shadow-rs/blob/909510eb5d265aaa69f605bd0e73eccbc343c785/src/gen_const.rs#L22

**Comment by baoyachi** [comment]
Hi @Nugine .
Can you provide a specific example, or perhaps a code sample? I'd like to try out how to solve your problem.

**Comment by Nugine** [comment]
```rust
//! crate_a

#[doc(hidden)]
pub use shadow_rs;

pub fn collect_info() {
    shadow_rs::new().unwrap();
    // and other logic ...
}

#[macro_export]
macro_rules! main {
    () => {
        use crate_a::shadow_rs;

        shadow_rs::shadow!(build);

        fn main() {
            println!("{}", build::VERSION);
            println!("{}", build::CLAP_LONG_VERSION);
            println!("{}", build::BRANCH);
            println!("{}", build::SHORT_COMMIT);
        }
    }
}
```

```rust
//! crate_b

crate_a::main!();
```

**Comment by baoyachi** [comment]
The reason for the compilation error above is that the build phase was placed in crate-b, but crate-b does not have shadow rs dependencies, resulting in the problem of not being able to find them.

Why not put build.rs in crate'a and export it for use?

for example:


* crate_a/src/lib.rs
```rust
shadow_rs::shadow!(build);
```

* crate_a/build.rs
```rust
fn main() {
	shadow_rs::new().unwrap();
}
```

* crate_a/Cargo.toml
```toml
[dependencies]
shadow-rs = "0.36"

[build-dependencies]
shadow-rs = "0.36"

```

* crate_b/main.rs
```rust
use crate_a::build;

fn main() {
    println!("{}", build::VERSION);
    println!("{}", build::CLAP_LONG_VERSION);
    println!("{}", build::BRANCH);
    println!("{}", build::SHORT_COMMIT);
}
```

**Comment by Nugine** [comment]
The build phase must be placed in crate_b in order to collect build info of crate_b. Otherwise it will generate the build info of crate_a.

**Comment by baoyachi** [comment]
If it is necessary to build on crate-b, it is still recommended to use shadow-rs dependencies directly on crate-b.

**Comment by Nugine** [comment]
There is a workaround that we can replace `shadow_rs` in `OUTDIR/shadow.rs` after calling `shadow_rs::new()`. So crate_b only need to depend on crate_a. It would be better if the renaming has built-in support.

**Comment by baoyachi** [comment]
Hi @Nugine  Welcome to your PR.

**Comment by baoyachi** [comment]
I will close it. If there is a problem, it can be reopened
