### ISSUE TITLE
What's the best way to make sure metadata is updated with every build?

### ISSUE THREAD

**Issue by petekubiak** [baoyachi/shadow-rs#193]
Hi, I'm trying out this crate to embed build metadata into the built binary, however I've noticed that the metadata doesn't update if the code hasn't changed since the last build:
![image](https://github.com/user-attachments/assets/676be948-5787-414a-8204-fb33cdb21a46)
(Note the difference between the current system time and the reported compile time)

Admittedly it could be argued that this is accurate as cached data built at the reported time has been used to generate the binary, however this becomes more of an issue with the commit hash and dirty flag. In this instance, the cache was created before my changes were committed, so in fact when this binary was created there is now a new commit hash and the build is no longer dirty.

To demonstrate, running `cargo clean && cargo run` now gives:
![image](https://github.com/user-attachments/assets/05ed8cc3-7272-4701-89dd-2638dc17b088)

I don't want to do this however, as I don't need all the dependencies to be rebuilt every time. I've tried adding
```rust
let out_dir = env::var("OUT_DIR").unwrap();
println!("cargo:rerun-if-changed={out_dir}/shadow.rs");
```
to the build script which seems to work, but I wondered if there are any alternatives?

Maybe it's worth adding this to the examples/docs if this is considered the best approach?

**Comment by baoyachi** [comment]
@petekubiak Thank you for your suggestion. I am considering optimizing it.

**Comment by baoyachi** [comment]
Hi @petekubiak ,apologies for the delayed response to this question. Additionally, the desired solution has finally arrived.

New version publised, please use :
```
shadow-rs = "0.37.0"
```

The code in build.rs, use `BuildPattern::RealTime` it will always trigger rebuilding a package.
Please see detail:https://github.com/baoyachi/shadow-rs?tab=readme-ov-file#buildpattern

```diff
fn main() {
	ShadowBuilder::builder()
+		.build_pattern(BuildPattern::RealTime)
		.build().unwrap();
}

```

**Comment by baoyachi** [comment]
I will close it. If there is a problem, it can be reopened.

**Comment by petekubiak** [comment]
Beautiful, nice work!
