### ISSUE TITLE
add debug print_build_in() function

### ISSUE THREAD

**Issue by baoyachi** [baoyachi/shadow-rs#51]
The idea from :https://github.com/dandavison/delta/issues/506

**Comment by baoyachi** [comment]
change `print_everything()` -> `print_build_in()` @dandavison

**Comment by baoyachi** [comment]
close:https://github.com/baoyachi/shadow-rs/pull/52

**Comment by dandavison** [comment]
Question about the name `print_build_in` -- is that an abbreviation for `print_build_information`? English speakers will recognize `_info` as an abbreviation, but they won't recognize `_in`.
