### ISSUE TITLE
RUST_VERSION and RUST_CHANNEL may disagree in presence of rust-toolchain.toml

### ISSUE THREAD

**Issue by imp** [baoyachi/shadow-rs#67]
`RUST_VERSION` is computed by running `rustc -V`, while `RUST_CHANNEL` by running `rustup default`
In presence of `rust-toolchain.toml` these may disagree.
Example: I have nightly configured by default (hence `rustup default` reports nightly channel), however in my crate I have

`rust-toolchain.toml`
```
[toolchain]
channel = "stable"
```

So, `rustc -V` reports the current stable version (as installed).
Understanding the discrepancy when these are reported by the running binary may be a tough exercise

**Comment by baoyachi** [comment]
Sorry,I haven't thought about this before. Thank for you report.

I'm try edit it.

**Comment by baoyachi** [comment]
It will be fix next version

**Comment by imp** [comment]
Thanks so much!

**Comment by baoyachi** [comment]
fix reference: https://rust-lang.github.io/rustup/overrides.html#toolchain-override-shorthand

## Unexpected cause e.g
* cargo +nightly test  
* cargo +stable test  
* use `rust-toolchain.toml` file define channel

## how to fix
* get std::env::vars("RUSTUP_TOOLCHAIN")

@imp

**Comment by baoyachi** [comment]
It's fixed with new version

```toml
[dependencies]
shadow-rs = "0.8.1"
```
