### ISSUE TITLE
Detect target features

### ISSUE THREAD

**Issue by epage** [baoyachi/shadow-rs#69]
In clap, we have https://github.com/clap-rs/clap/issues/1363.  I'm tempted to close this out by pointing to shadow.  One thing mentioned in that issue but that I'm not seeing in shadow is checking `target_feature` support (simd flags).

**Comment by baoyachi** [comment]
It may be similar to this issue. https://github.com/baoyachi/shadow-rs/issues/53

Do you have any good suggestions. @epage

**Comment by epage** [comment]
One idea I have is to create a non-exhaustive enum that either has an `as_str` or derefs to `str` that has the string version of the enum (which `Display` wraps).  Then its just a matter of code-genning that similarly to the code in the clap issue.

I can take a crack at this tomorrow if you want.

**Comment by baoyachi** [comment]
Yeah，I look forward to your pr
