### ISSUE TITLE
Distinguish between `clap::App::version` and `clap::App::long_version`

### ISSUE THREAD

**Issue by epage** [baoyachi/shadow-rs#70]
I'm wondering if `clap_version` should be renamed to `clap_long_version` for encouraging its use with [`clap::App::long_version`](https://docs.rs/clap/latest/clap/struct.App.html#method.long_version) rather than [`clap::App::version`](https://docs.rs/clap/latest/clap/struct.App.html#method.version).

**Comment by baoyachi** [comment]
Yeah, I think this makes sense. Update later @epage
