### ISSUE TITLE
Consider replacing the chrono crates with security 

### ISSUE THREAD

**Issue by baoyachi** [baoyachi/shadow-rs#72]
ref:https://github.com/baoyachi/shadow-rs/issues/71

**Comment by baoyachi** [comment]
use [time](https://crates.io/crates/time) crates replace with [chrono](https://crates.io/crates/chrono)

**Comment by coderedart** [comment]
although its not really a security issue, this is slightly annoying because it fails the CI check. `time 0.3.11` does not trigger any security advisory atleast.

**Comment by baoyachi** [comment]
Solution: Consider the following two creates

* https://docs.rs/time
* https://docs.rs/tz-rs

**Comment by baoyachi** [comment]
Close now, and reopen it if there is a problem.
