### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jaskij** [baoyachi/shadow-rs#87]
Today, I noticed a new version of `shadow`, `0.11.0`.

I wanted to check whether it makes sense to upgrade the dependency in my `Cargo.toml`, but there is no changelog, and the GH releases aren't very informative either.

Is there any changelog I can find? If no, could you please consider keeping one for future versions?

**Comment by baoyachi** [comment]
@jaskij DONE. Use this tool:https://github.com/orhun/git-cliff
