### ISSUE TITLE
GitLab/Github CI support

### ISSUE THREAD

**Issue by jaskij** [baoyachi/shadow-rs#90]
GitLab CI exposes a fair number of information about the job in the form of [environment variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). Would you be open to supporting them behind a feature flag? Something similar probably goes for GitHub, but I have no experience with their CI.

**Comment by baoyachi** [comment]
I would like to. 

Could you please provide detail example about?

**Comment by jaskij** [comment]
Here's the [full reference](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html).

Not all of the might be applicable, definitely `CI_JOB_*` and `CI_PIPELINE_*` are probably reasonable. `CI_COMMIT_*` is probably redundant. I'd exclude authorization-related stuff.
